In [1]:
# Import das bibliotecas
import numpy as np

**Exercício 01**

Construa o operador linear diagonalizável $T:\mathbb{R}^3 \to \mathbb{R}^3$ que tenha $2$ e $9$ como autovalores de modo que os autoespaços sejam $V(2) = [(1,2,0),(0,6,1)]$ e $V(9) = [(1,1,1)]$.

In [2]:
# Autovalores
v_1 = 2
v_2 = 9

# Autovetores
V_2 = np.array([[1,2,0],[0,6,1]])
V_9 = np.array([[1,1,1]])

In [3]:
# Matriz coluna dos autovetores
P = np.column_stack([V_2[0], V_2[1], V_9[0]])

print(P)

[[1 0 1]
 [2 6 1]
 [0 1 1]]


In [4]:
# Matriz diagonal dos autovalores
D = np.diag([2,2,9])

print(D)

[[2 0 0]
 [0 2 0]
 [0 0 9]]


In [5]:
# T = P . D . P⁻¹
T = P @ D @ np.linalg.inv(P)

print(T)

[[ 4. -1.  6.]
 [ 2.  1.  6.]
 [ 2. -1.  8.]]


In [6]:
# Verificando
v1 = V_2[0]
Tv1 = T @ v1
lambda_v1 = v_1 * v1

print("v1 = ", v1)
print("T(v1) = ", Tv1)
print("2*v1 = ", lambda_v1)

v1 =  [1 2 0]
T(v1) =  [2. 4. 0.]
2*v1 =  [2 4 0]


In [7]:
# Verificando
v2 = V_2[1]
Tv2 = T @ v2
lambda_v2 = v_1 * v2

print("v2 = ", v2)
print("T(v2) = ", Tv2)
print("2*v2 = ", lambda_v2)

v2 =  [0 6 1]
T(v2) =  [ 0. 12.  2.]
2*v2 =  [ 0 12  2]


In [8]:
# Verificando
v3 = V_9[0]
Tv3 = T @ v3
lambda_v3 = v_2 * v3

print("v3 = ", v3)
print("T(v3) = ", Tv3)
print("9*v3 = ", lambda_v3)

v3 =  [1 1 1]
T(v3) =  [9. 9. 9.]
9*v3 =  [9 9 9]


**Exercício 02**

Construa uma transformação linear que mapeia o vetor $\mathbf{v}=[1,1,1,1,1]\in\mathbb{R}^5$ nele mesmo, ou seja, a transformação deve satisfazer $\mathbf{A}\mathbf{v}=\mathbf{v}$.

In [9]:
v = np.array([1,1,1,1,1])

# Matriz identidade 5x5
I = np.eye(5)

print(I)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
# Transformação
Tv = I @ v

print("v = ", v)
print("T(v) = ", Tv)

v =  [1 1 1 1 1]
T(v) =  [1. 1. 1. 1. 1.]
