



#### Exercício - Subespaço Gerado

Seja $W$ o subespaço de $M_{3\times2}(\mathbb{R})$ gerado pelas matrizes

$$A_1 = \begin{bmatrix} 0 & 0 \\ 1 & 1 \\ 0 & 0 \end{bmatrix} , \;
A_2 = \begin{bmatrix} 0 & 1 \\ 0 & -1 \\ 1 & 0 \end{bmatrix} \; \text{e} \;
A_3 = \begin{bmatrix} 0 & 1 \\ 0 & 0 \\ 0 & 0 \end{bmatrix} .$$

Implemente um código para verificar se a matriz $$A = \begin{bmatrix} 0 & 2 \\ 3 & 4 \\ 5 & 0 \end{bmatrix}$$ pertence ao subespaço $W$.

In [12]:
import numpy as np

A1 = np.array([[0,0], [1,1], [0,0]])
A2 = np.array([[0,1], [0,-1], [1,0]])
A3 = np.array([[0,1], [0,0], [0,0]])
A = np.array([[0,2], [3,4], [5,0]])

print("A1: ", A1)
print("A2: ", A2)
print("A3: ", A3)
print("A : ", A)

A1:  [[0 0]
 [1 1]
 [0 0]]
A2:  [[ 0  1]
 [ 0 -1]
 [ 1  0]]
A3:  [[0 1]
 [0 0]
 [0 0]]
A :  [[0 2]
 [3 4]
 [5 0]]


Matrizes na forma de vetores de vetores.

In [30]:
A1 = A1.flatten()
A2 = A2.flatten()
A3 = A3.flatten()
A = A.flatten()

print("A1: ", A1)
print("A2: ", A2)
print("A3: ", A3)
print("A : ", A)

A1:  [0 0 1 1 0 0]
A2:  [ 0  1  0 -1  1  0]
A3:  [0 1 0 0 0 0]
A :  [0 2 3 4 5 0]


A função flatten reduz uma dimensão das matrizes, transformando-as em um vetor simples (dimensão 1), necessário para usarmos o linalg.solve (matrizes quadradas).

In [33]:
M = np.column_stack([A1, A2, A3])

print("M: ", M)
print("A : ", A)

M:  [[ 0  0  0]
 [ 0  1  1]
 [ 1  0  0]
 [ 1 -1  0]
 [ 0  1  0]
 [ 0  0  0]]
A :  [0 2 3 4 5 0]


In [34]:
print(np.linalg.solve(M, A))

LinAlgError: Last 2 dimensions of the array must be square

Não funciona pois temos mais equações que variáveis (linalg.solve só resolve equações lineares definidas).

In [39]:
resposta, residuos, _, _ = np.linalg.lstsq(M, A)
print(resposta)
print(residuos)

[ 5.  3. -1.]
[12.]


A presença de resíduos (residuos != 0) indica que há um erro entre o valor obtido e real, o que indica que o sistema não tem solução. Disso temos que A não pertence ao subespaço W.